package io.crm.app.model.smstemplate;
public enum SmsTemplateSortItem {

    SMS_TEMPLATE_ID_ASC,
    SMS_TEMPLATE_ID_DESC,

    SMS_TEMPLATE_NAME_ASC,
    SMS_TEMPLATE_NAME_DESC,

    SMS_TEMPLATE_CONTENT_ASC,
    SMS_TEMPLATE_CONTENT_DESC,

    CREATED_TIMESTAMP_ASC,
    UPDATED_TIMESTAMP_DESC;
}
